project_id = "iacqjjkxxcbwpkvmlojn"

[functions.chat-with-alli]
verify_jwt = true

[functions.create-checkout]
verify_jwt = false

[functions.create-freemium-subscription]
verify_jwt = false

[functions.generate-alli-image]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false
